<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>System Status Report</title>
    <style>
        /* dompdf only understands a subset of CSS: no flexbox/grid, so
           this template sticks to block/table layout and inline-safe
           properties. */
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #1a1a1a;
            margin: 0;
        }
        .header {
            border-bottom: 2px solid #0F766E;
            padding-bottom: 10px;
            margin-bottom: 14px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0 0 4px 0;
            color: #0F766E;
        }
        .meta-table {
            width: 100%;
            margin-bottom: 4px;
        }
        .meta-table td {
            font-size: 10px;
            color: #444;
            padding: 1px 0;
        }
        .meta-table td.label {
            width: 110px;
            color: #777;
        }
        .summary-box {
            border: 1px solid #ddd;
            background: #f5f7f7;
            padding: 8px 10px;
            margin-bottom: 18px;
        }
        .summary-box table {
            width: 100%;
        }
        .summary-box td {
            font-size: 11px;
            text-align: center;
            padding: 2px 0;
        }
        .summary-box .num {
            font-size: 16px;
            font-weight: bold;
            color: #0F766E;
        }
        h2.section-title {
            font-size: 13px;
            color: #0F766E;
            border-bottom: 1px solid #ccc;
            padding-bottom: 4px;
            margin: 18px 0 8px 0;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 6px;
        }
        table.data-table th {
            background: #0F766E;
            color: #fff;
            font-size: 9.5px;
            text-align: left;
            padding: 5px 6px;
            text-transform: uppercase;
        }
        table.data-table td {
            font-size: 10px;
            padding: 5px 6px;
            border-bottom: 1px solid #e5e5e5;
        }
        table.data-table tr:nth-child(even) td {
            background: #fafafa;
        }
        .status {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
            color: #fff;
        }
        .status-online  { background: #16A34A; }
        .status-idle    { background: #D97706; }
        .status-offline { background: #DC2626; }
        .footer {
            margin-top: 24px;
            padding-top: 8px;
            border-top: 1px solid #ddd;
            font-size: 9px;
            color: #888;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>System Status Report</h1>
        <table class="meta-table">
            <tr>
                <td class="label">Report Date/Time:</td>
                <td>{{ $generatedAt->format('F d, Y — h:i A') }} (Asia/Manila)</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ $generatedBy }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <table>
            <tr>
                <td>
                    <div class="num">{{ $airQualityCounts['online'] + $seismicCounts['online'] }}</div>
                    Online
                </td>
                <td>
                    <div class="num">{{ $airQualityCounts['idle'] + $seismicCounts['idle'] }}</div>
                    Idle
                </td>
                <td>
                    <div class="num">{{ $airQualityCounts['offline'] + $seismicCounts['offline'] }}</div>
                    Offline
                </td>
                <td>
                    <div class="num">{{ count($airQualityData) + count($seismicData) }}</div>
                    Total Stations
                </td>
            </tr>
        </table>
    </div>

    {{-- ---------- Air Quality ---------- --}}
    <h2 class="section-title">
        Air Quality Stations
        ({{ $airQualityCounts['online'] }} online / {{ count($airQualityData) }} total)
    </h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Station</th>
                <th>Location</th>
                <th>Installed</th>
                <th>Latest Reading</th>
                <th>Total Data</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($airQualityData as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->station }}</td>
                    <td>{{ $item->location ?? '—' }}</td>
                    <td>{{ $item->installed_at ? \Carbon\Carbon::parse($item->installed_at)->format('Y-m-d') : '—' }}</td>
                    <td>{{ $item->latest_at ? \Carbon\Carbon::parse($item->latest_at)->format('Y-m-d H:i') : '—' }}</td>
                    <td>{{ number_format($item->total) }}</td>
                    <td>
                        <span class="status status-{{ $item->status }}">{{ ucfirst($item->status) }}</span>
                    </td>
                </tr>
            @empty
                <tr><td colspan="7">No air quality data available</td></tr>
            @endforelse
        </tbody>
    </table>

    {{-- ---------- Seismic ---------- --}}
    <h2 class="section-title">
        Seismic Stations
        ({{ $seismicCounts['online'] }} online / {{ count($seismicData) }} total)
    </h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Station</th>
                <th>Location (Lat, Long)</th>
                <th>Installed</th>
                <th>Latest Reading</th>
                <th>Total Data</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($seismicData as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->station }}</td>
                    <td>{{ $item->location ?? '—' }}</td>
                    <td>{{ $item->installed_at ? \Carbon\Carbon::parse($item->installed_at)->format('Y-m-d') : '—' }}</td>
                    <td>{{ $item->latest_at ? \Carbon\Carbon::parse($item->latest_at)->format('Y-m-d H:i') : '—' }}</td>
                    <td>{{ number_format($item->total) }}</td>
                    <td>
                        <span class="status status-{{ $item->status }}">{{ ucfirst($item->status) }}</span>
                    </td>
                </tr>
            @empty
                <tr><td colspan="7">No seismic data available</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        This report reflects station status at the time it was generated and may not match a subsequently refreshed dashboard.
    </div>

</body>
</html>